---
title: "Task 7: Lab 3"
author: "Parker Davis"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code for Plot and Widgets

Here is the modified code for the Spruce plots widget. 

```{r slr, echo=FALSE}
library(ggplot2)
# DATA
spruce.df = read.csv("SPRUCE.csv")#MS pg478
fin.df = read.csv("FINTUBES.csv")

# INPUTS
inputPanel(
  
  
  selectInput("plotg", "Choose plot type",
      list("Combined", "Points", "Points with Line Segments", "Simple     Linear Regression Line"
      )
    )
)

renderPlot({
  
 g = ggplot(spruce.df, aes(x = BHDiameter, y = Height, color = Height)) + geom_point() 

 grl = ggplot(spruce.df, aes(x= BHDiameter, y= Height)) + geom_smooth(method="lm")
 
 gpl = g + geom_line()
 
 gc = ggplot(spruce.df, aes(x=BHDiameter,y=Height, color=Height))+geom_point() + geom_line()+ geom_smooth(method="lm")
 
 if(input$plotg == "Combined")
 {
   print(gc)
   ggsave("Combined.png", path = getwd())
 }
 if(input$plotg == "Points")
   {print(g)
   ggsave("points.png", path=getwd())
   } 
 
 if(input$plotg == "Points with Line Segments"){
   print(gpl)
   ggsave("LineSeg.png", path = getwd())
   
 }
 
 if(input$plotg == "Simple     Linear Regression Line")
 {
   print(grl)
   ggsave("RegLine.png", path = getwd())
   
 }

 

 
   
})
```
